"""empty message

Revision ID: 3e680e3956dc
Revises: 
Create Date: 2022-12-27 22:30:30.923439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e680e3956dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.String(length=10), nullable=False),
    sa.Column('doctor_level', sa.String(length=12), nullable=False),
    sa.Column('doctor_kind', sa.String(length=11), nullable=True),
    sa.Column('doctor_Belonging', sa.String(length=12), nullable=False),
    sa.Column('doctor_score', sa.String(length=11), nullable=True),
    sa.Column('doctor_inquiry', sa.String(length=12), nullable=False),
    sa.Column('doctor_goodFor', sa.String(length=255), nullable=False),
    sa.Column('pic_see_price', sa.String(length=255), nullable=False),
    sa.Column('video_see_price', sa.String(length=255), nullable=False),
    sa.Column('doctor_detail', sa.String(length=255), nullable=False),
    sa.Column('rdatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_kind'),
    sa.UniqueConstraint('doctor_score')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_info')
    # ### end Alembic commands ###
